# Generated by Django 4.1.3 on 2022-11-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ad_author_id_ad_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="ad",
            old_name="category_id",
            new_name="category",
        ),
    ]
